name: Sync to Gitee
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        with:
          target-repo: git@gitee.com:NsdcN/56Account.git
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_KEY }}

